stages:
  - Unit Tests
  - Poetry Build
  - Docker Build

variables:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.1.5

.poetry_image:
  image: python:$PYTHON_VERSION
  before_script:
    - echo "Fetching & Installing Poetry"
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - $([ ! -z $POETRY_VERSION ] && echo "--version $POETRY_VERSION")
    - echo "Configuring Current Shell"
    - source $HOME/.poetry/env

Run Unit Tests:
  stage: Unit Tests
  extends:
    - .poetry_image
  script:
    - poetry install
    - poetry run pytest

Build with Poetry:
  stage: Poetry Build
  extends:
    - .poetry_image
  script:
    - echo "Building Project"
    - poetry build
    - echo "Extracting Version"
    - poetry version -s > ./version
  artifacts:
    paths:
      - dist/*
      - ./version
